/** ISO2 → NL display name + search aliases in all app locales. */
export const COUNTRY_META: Record<string, { name: string; aliases: string[] }> = {
  AE: { name: "Verenigde Arabische Emiraten", aliases: ["United Arab Emirates", "阿拉伯联合酋长国", "สหรัฐอาหรับเอมิเรตส์", "Vereinigte Arabische Emirate", "ОАЭ", "アラブ首長国連邦", "아랍에미리트", "Các Tiểu Vương quốc Ả Rập Thống nhất", "Uni Emirat Arab", "Emiratos Árabes Unidos", "uae", "emirates", "united arab emirates", "emiratos"] },
  AF: { name: "Afghanistan", aliases: ["阿富汗", "อัฟกานิสถาน", "Афганистан", "アフガニスタン", "아프가니스탄", "Afganistan", "Afganistán"] },
  AG: { name: "Antigua en Barbuda", aliases: ["Antigua & Barbuda", "安提瓜和巴布达", "แอนติกาและบาร์บูดา", "Antigua und Barbuda", "Антигуа и Барбуда", "アンティグア・バーブーダ", "앤티가 바부다", "Antigua và Barbuda", "Antigua dan Barbuda", "Antigua y Barbuda"] },
  AI: { name: "Anguilla", aliases: ["安圭拉", "แองกวิลลา", "Ангилья", "アンギラ", "앵귈라", "Anguila"] },
  AL: { name: "Albanië", aliases: ["Albania", "阿尔巴尼亚", "แอลเบเนีย", "Albanien", "Албания", "アルバニア", "알바니아"] },
  AM: { name: "Armenië", aliases: ["Armenia", "亚美尼亚", "อาร์เมเนีย", "Armenien", "Армения", "アルメニア", "아르메니아"] },
  AO: { name: "Angola", aliases: ["安哥拉", "แองโกลา", "Ангола", "アンゴラ", "앙골라"] },
  AR: { name: "Argentinië", aliases: ["Argentina", "阿根廷", "อาร์เจนตินา", "Argentinien", "Аргентина", "アルゼンチン", "아르헨티나"] },
  AS: { name: "Amerikaans-Samoa", aliases: ["American Samoa", "美属萨摩亚", "อเมริกันซามัว", "Amerikanisch-Samoa", "Американское Самоа", "米領サモア", "아메리칸 사모아", "Samoa thuộc Mỹ", "Samoa Amerika", "Samoa Americana"] },
  AT: { name: "Oostenrijk", aliases: ["Austria", "奥地利", "ออสเตรีย", "Österreich", "Австрия", "オーストリア", "오스트리아", "Áo", "austria", "österreich", "австрия"] },
  AU: { name: "Australië", aliases: ["Australia", "澳大利亚", "ออสเตรเลีย", "Australien", "Австралия", "オーストラリア", "오스트레일리아", "Úc", "australia", "australie", "australien", "호주", "австралия"] },
  AW: { name: "Aruba", aliases: ["阿鲁巴", "อารูบา", "Аруба", "アルバ", "아루바"] },
  AZ: { name: "Azerbeidzjan", aliases: ["Azerbaijan", "阿塞拜疆", "อาเซอร์ไบจาน", "Aserbaidschan", "Азербайджан", "アゼルバイジャン", "아제르바이잔", "Azerbaiyán"] },
  BA: { name: "Bosnië en Herzegovina", aliases: ["Bosnia & Herzegovina", "波斯尼亚和黑塞哥维那", "บอสเนียและเฮอร์เซโกวีนา", "Bosnien und Herzegowina", "Босния и Герцеговина", "ボスニア・ヘルツェゴビナ", "보스니아 헤르체고비나", "Bosnia và Herzegovina", "Bosnia dan Herzegovina", "Bosnia y Herzegovina"] },
  BB: { name: "Barbados", aliases: ["巴巴多斯", "บาร์เบโดส", "Барбадос", "バルバドス", "바베이도스"] },
  BD: { name: "Bangladesh", aliases: ["孟加拉国", "บังกลาเทศ", "Bangladesch", "Бангладеш", "バングラデシュ", "방글라데시", "Bangladés"] },
  BE: { name: "België", aliases: ["Belgium", "比利时", "เบลเยียม", "Belgien", "Бельгия", "ベルギー", "벨기에", "Bỉ", "Belgia", "Bélgica", "belgium", "belgie", "belgien", "bélgica", "бельгия"] },
  BF: { name: "Burkina Faso", aliases: ["布基纳法索", "บูร์กินาฟาโซ", "Буркина-Фасо", "ブルキナファソ", "부르키나파소"] },
  BG: { name: "Bulgarije", aliases: ["Bulgaria", "保加利亚", "บัลแกเรีย", "Bulgarien", "Болгария", "ブルガリア", "불가리아"] },
  BH: { name: "Bahrein", aliases: ["Bahrain", "巴林", "บาห์เรน", "Бахрейн", "バーレーン", "바레인", "Baréin"] },
  BI: { name: "Burundi", aliases: ["布隆迪", "บุรุนดี", "Бурунди", "ブルンジ", "부룬디"] },
  BJ: { name: "Benin", aliases: ["贝宁", "เบนิน", "Бенин", "ベナン", "베냉", "Benín"] },
  BL: { name: "Saint-Barthélemy", aliases: ["St. Barthélemy", "圣巴泰勒米", "เซนต์บาร์เธเลมี", "Сен-Бартелеми", "サン・バルテルミー", "생바르텔레미", "Saint Barthélemy", "San Bartolomé"] },
  BM: { name: "Bermuda", aliases: ["百慕大", "เบอร์มิวดา", "Бермудские о-ва", "バミューダ", "버뮤다", "Bermudas"] },
  BN: { name: "Brunei", aliases: ["文莱", "บรูไน", "Brunei Darussalam", "Бруней", "ブルネイ", "브루나이", "Brunéi"] },
  BO: { name: "Bolivia", aliases: ["玻利维亚", "โบลิเวีย", "Bolivien", "Боливия", "ボリビア", "볼리비아"] },
  BQ: { name: "Caribisch Nederland", aliases: ["Caribbean Netherlands", "荷属加勒比区", "เนเธอร์แลนด์แคริบเบียน", "Karibische Niederlande", "Бонэйр, Синт-Эстатиус и Саба", "オランダ領カリブ", "네덜란드령 카리브", "Ca-ri-bê Hà Lan", "Belanda Karibia", "Caribe neerlandés", "bonaire", "saba", "sint eustatius"] },
  BR: { name: "Brazilië", aliases: ["Brazil", "巴西", "บราซิล", "Brasilien", "Бразилия", "ブラジル", "브라질", "Brasil", "brazil", "brazilie", "brasil", "brasilien", "бразилия"] },
  BS: { name: "Bahama’s", aliases: ["Bahamas", "巴哈马", "บาฮามาส", "Багамы", "バハマ", "바하마", "Bahama", "bahamas", "bahama's"] },
  BT: { name: "Bhutan", aliases: ["不丹", "ภูฏาน", "Бутан", "ブータン", "부탄", "Bután"] },
  BW: { name: "Botswana", aliases: ["博茨瓦纳", "บอตสวานา", "Botsuana", "Ботсвана", "ボツワナ", "보츠와나"] },
  BY: { name: "Belarus", aliases: ["白俄罗斯", "เบลารุส", "Беларусь", "ベラルーシ", "벨라루스", "Bielorrusia"] },
  BZ: { name: "Belize", aliases: ["伯利兹", "เบลีซ", "Белиз", "ベリーズ", "벨리즈", "Belice"] },
  CA: { name: "Canada", aliases: ["加拿大", "แคนาดา", "Kanada", "Канада", "カナダ", "캐나다", "Canadá", "kanada", "канада"] },
  CC: { name: "Cocoseilanden", aliases: ["Cocos (Keeling) Islands", "科科斯（基林）群岛", "หมู่เกาะโคโคส (คีลิง)", "Kokosinseln", "Кокосовые о-ва", "ココス(キーリング)諸島", "코코스 제도", "Quần đảo Cocos (Keeling)", "Kepulauan Cocos (Keeling)", "Islas Cocos"] },
  CD: { name: "Congo-Kinshasa", aliases: ["Congo - Kinshasa", "刚果（金）", "คองโก - กินชาซา", "Kongo-Kinshasa", "Конго - Киншаса", "コンゴ民主共和国(キンシャサ)", "콩고-킨샤사", "Kongo - Kinshasa", "República Democrática del Congo", "congo", "drc", "dr congo", "democratische republiek congo"] },
  CF: { name: "Centraal-Afrikaanse Republiek", aliases: ["Central African Republic", "中非共和国", "สาธารณรัฐแอฟริกากลาง", "Zentralafrikanische Republik", "Центрально-Африканская Республика", "中央アフリカ共和国", "중앙 아프리카 공화국", "Cộng hòa Trung Phi", "Republik Afrika Tengah", "República Centroafricana"] },
  CG: { name: "Congo-Brazzaville", aliases: ["Congo - Brazzaville", "刚果（布）", "คองโก - บราซซาวิล", "Kongo-Brazzaville", "Конго - Браззавиль", "コンゴ共和国(ブラザビル)", "콩고-브라자빌", "Kongo - Brazzaville", "Congo", "republic of the congo"] },
  CH: { name: "Zwitserland", aliases: ["Switzerland", "瑞士", "สวิตเซอร์แลนด์", "Schweiz", "Швейцария", "スイス", "스위스", "Thụy Sĩ", "Swiss", "Suiza", "switzerland", "schweiz", "suiza", "швейцария"] },
  CI: { name: "Ivoorkust", aliases: ["Côte d’Ivoire", "科特迪瓦", "โกตดิวัวร์", "Кот-д’Ивуар", "コートジボワール", "코트디부아르", "ivory coast", "cote divoire", "côte d'ivoire", "elfenbeinküste", "costa de marfil"] },
  CK: { name: "Cookeilanden", aliases: ["Cook Islands", "库克群岛", "หมู่เกาะคุก", "Cookinseln", "о-ва Кука", "クック諸島", "쿡 제도", "Quần đảo Cook", "Kepulauan Cook", "Islas Cook"] },
  CL: { name: "Chili", aliases: ["Chile", "智利", "ชิลี", "Чили", "チリ", "칠레", "Cile"] },
  CM: { name: "Kameroen", aliases: ["Cameroon", "喀麦隆", "แคเมอรูน", "Kamerun", "Камерун", "カメルーン", "카메룬", "Camerún"] },
  CN: { name: "China", aliases: ["中国", "จีน", "Китай", "중국", "Trung Quốc", "Tiongkok", "китай", "tiongkok", "trung quốc"] },
  CO: { name: "Colombia", aliases: ["哥伦比亚", "โคลอมเบีย", "Kolumbien", "Колумбия", "コロンビア", "콜롬비아", "Kolombia"] },
  CR: { name: "Costa Rica", aliases: ["哥斯达黎加", "คอสตาริกา", "Коста-Рика", "コスタリカ", "코스타리카", "Kosta Rika"] },
  CU: { name: "Cuba", aliases: ["古巴", "คิวบา", "Kuba", "Куба", "キューバ", "쿠바"] },
  CV: { name: "Kaapverdië", aliases: ["Cape Verde", "佛得角", "เคปเวิร์ด", "Cabo Verde", "Кабо-Верде", "カーボベルデ", "카보베르데", "Tanjung Verde"] },
  CW: { name: "Curaçao", aliases: ["库拉索", "คูราเซา", "Кюрасао", "キュラソー", "퀴라소", "Curazao"] },
  CX: { name: "Christmaseiland", aliases: ["Christmas Island", "圣诞岛", "เกาะคริสต์มาส", "Weihnachtsinsel", "о-в Рождества", "クリスマス島", "크리스마스섬", "Đảo Giáng Sinh", "Pulau Natal", "Isla de Navidad"] },
  CY: { name: "Cyprus", aliases: ["塞浦路斯", "ไซปรัส", "Zypern", "Кипр", "キプロス", "키프로스", "Síp", "Siprus", "Chipre"] },
  CZ: { name: "Tsjechië", aliases: ["Czechia", "捷克", "เช็ก", "Tschechien", "Чехия", "チェコ", "체코", "Séc", "Ceko", "Chequia"] },
  DE: { name: "Duitsland", aliases: ["Germany", "德国", "เยอรมนี", "Deutschland", "Германия", "ドイツ", "독일", "Đức", "Jerman", "Alemania", "germany", "deutschland", "alemania", "jerman", "германия"] },
  DJ: { name: "Djibouti", aliases: ["吉布提", "จิบูตี", "Dschibuti", "Джибути", "ジブチ", "지부티", "Jibuti", "Yibuti"] },
  DK: { name: "Denemarken", aliases: ["Denmark", "丹麦", "เดนมาร์ก", "Dänemark", "Дания", "デンマーク", "덴마크", "Đan Mạch", "Dinamarca"] },
  DM: { name: "Dominica", aliases: ["多米尼克", "โดมินิกา", "Доминика", "ドミニカ国", "도미니카", "Dominika"] },
  DO: { name: "Dominicaanse Republiek", aliases: ["Dominican Republic", "多米尼加共和国", "สาธารณรัฐโดมินิกัน", "Dominikanische Republik", "Доминиканская Республика", "ドミニカ共和国", "도미니카 공화국", "Cộng hòa Dominica", "Republik Dominika", "República Dominicana", "dominican republic", "dominicaanse", "república dominicana"] },
  DZ: { name: "Algerije", aliases: ["Algeria", "阿尔及利亚", "แอลจีเรีย", "Algerien", "Алжир", "アルジェリア", "알제리", "Aljazair", "Argelia"] },
  EC: { name: "Ecuador", aliases: ["厄瓜多尔", "เอกวาดอร์", "Эквадор", "エクアドル", "에콰도르", "Ekuador"] },
  EE: { name: "Estland", aliases: ["Estonia", "爱沙尼亚", "เอสโตเนีย", "Эстония", "エストニア", "에스토니아"] },
  EG: { name: "Egypte", aliases: ["Egypt", "埃及", "อียิปต์", "Ägypten", "Египет", "エジプト", "이집트", "Ai Cập", "Mesir", "Egipto", "egypt", "ägypten", "egipto", "египет"] },
  EH: { name: "Westelijke Sahara", aliases: ["Western Sahara", "西撒哈拉", "ซาฮาราตะวันตก", "Westsahara", "Западная Сахара", "西サハラ", "서사하라", "Tây Sahara", "Sahara Barat", "Sáhara Occidental", "western sahara", "westsahara", "sáhara occidental"] },
  ER: { name: "Eritrea", aliases: ["厄立特里亚", "เอริเทรีย", "Эритрея", "エリトリア", "에리트리아"] },
  ES: { name: "Spanje", aliases: ["Spain", "西班牙", "สเปน", "Spanien", "Испания", "スペイン", "스페인", "Tây Ban Nha", "Spanyol", "España", "spain", "spanien", "españa", "spanyol", "испания"] },
  ET: { name: "Ethiopië", aliases: ["Ethiopia", "埃塞俄比亚", "เอธิโอเปีย", "Äthiopien", "Эфиопия", "エチオピア", "에티오피아", "Etiopia", "Etiopía"] },
  FI: { name: "Finland", aliases: ["芬兰", "ฟินแลนด์", "Finnland", "Финляндия", "フィンランド", "핀란드", "Phần Lan", "Finlandia"] },
  FJ: { name: "Fiji", aliases: ["斐济", "ฟิจิ", "Fidschi", "Фиджи", "フィジー", "피지", "Fiyi"] },
  FK: { name: "Falklandeilanden", aliases: ["Falkland Islands", "福克兰群岛", "หมู่เกาะฟอล์กแลนด์", "Falklandinseln", "Фолклендские о-ва", "フォークランド諸島", "포클랜드 제도", "Quần đảo Falkland", "Kepulauan Falkland", "Islas Malvinas", "falkland", "malvinas", "islas malvinas"] },
  FM: { name: "Micronesia", aliases: ["密克罗尼西亚", "ไมโครนีเซีย", "Mikronesien", "Федеративные Штаты Микронезии", "ミクロネシア連邦", "미크로네시아", "Mikronesia"] },
  FO: { name: "Faeröer", aliases: ["Faroe Islands", "法罗群岛", "หมู่เกาะแฟโร", "Färöer", "Фарерские о-ва", "フェロー諸島", "페로 제도", "Quần đảo Faroe", "Kepulauan Faroe", "Islas Feroe"] },
  FR: { name: "Frankrijk", aliases: ["France", "法国", "ฝรั่งเศส", "Frankreich", "Франция", "フランス", "프랑스", "Pháp", "Prancis", "Francia", "france", "frankreich", "франция", "perancis", "pháp"] },
  GA: { name: "Gabon", aliases: ["加蓬", "กาบอง", "Gabun", "Габон", "ガボン", "가봉", "Gabón"] },
  GB: { name: "Verenigd Koninkrijk", aliases: ["United Kingdom", "英国", "สหราชอาณาจักร", "Vereinigtes Königreich", "Великобритания", "イギリス", "영국", "Vương quốc Anh", "Inggris Raya", "Reino Unido", "uk", "england", "britain", "great britain", "groot-brittannie", "groot-brittannië", "อังกฤษ", "inggris", "anh"] },
  GD: { name: "Grenada", aliases: ["格林纳达", "เกรเนดา", "Гренада", "グレナダ", "그레나다", "Granada"] },
  GE: { name: "Georgië", aliases: ["Georgia", "格鲁吉亚", "จอร์เจีย", "Georgien", "Грузия", "ジョージア", "조지아"] },
  GF: { name: "Frans-Guyana", aliases: ["French Guiana", "法属圭亚那", "เฟรนช์เกียนา", "Französisch-Guayana", "Французская Гвиана", "仏領ギアナ", "프랑스령 기아나", "Guiana thuộc Pháp", "Guyana Prancis", "Guayana Francesa"] },
  GG: { name: "Guernsey", aliases: ["根西岛", "เกิร์นซีย์", "Гернси", "ガーンジー", "건지", "Guernesey"] },
  GH: { name: "Ghana", aliases: ["加纳", "กานา", "Гана", "ガーナ", "가나"] },
  GI: { name: "Gibraltar", aliases: ["直布罗陀", "ยิบรอลตาร์", "Гибралтар", "ジブラルタル", "지브롤터"] },
  GL: { name: "Groenland", aliases: ["Greenland", "格陵兰", "กรีนแลนด์", "Grönland", "Гренландия", "グリーンランド", "그린란드", "Groenlandia"] },
  GM: { name: "Gambia", aliases: ["冈比亚", "แกมเบีย", "Гамбия", "ガンビア", "감비아"] },
  GN: { name: "Guinee", aliases: ["Guinea", "几内亚", "กินี", "Гвинея", "ギニア", "기니"] },
  GP: { name: "Guadeloupe", aliases: ["瓜德罗普", "กวาเดอลูป", "Гваделупа", "グアドループ", "과들루프", "Guadalupe"] },
  GQ: { name: "Equatoriaal-Guinea", aliases: ["Equatorial Guinea", "赤道几内亚", "อิเควทอเรียลกินี", "Äquatorialguinea", "Экваториальная Гвинея", "赤道ギニア", "적도 기니", "Guinea Xích Đạo", "Guinea Ekuatorial", "Guinea Ecuatorial"] },
  GR: { name: "Griekenland", aliases: ["Greece", "希腊", "กรีซ", "Griechenland", "Греция", "ギリシャ", "그리스", "Hy Lạp", "Yunani", "Grecia", "greece", "griechenland", "grecia", "yunani", "греция"] },
  GT: { name: "Guatemala", aliases: ["危地马拉", "กัวเตมาลา", "Гватемала", "グアテマラ", "과테말라"] },
  GU: { name: "Guam", aliases: ["关岛", "กวม", "Гуам", "グアム"] },
  GW: { name: "Guinee-Bissau", aliases: ["Guinea-Bissau", "几内亚比绍", "กินี-บิสเซา", "Гвинея-Бисау", "ギニアビサウ", "기니비사우", "Guinea-Bisáu"] },
  GY: { name: "Guyana", aliases: ["圭亚那", "กายอานา", "Гайана", "ガイアナ", "가이아나"] },
  HK: { name: "Hongkong", aliases: ["Hong Kong SAR China", "Hongkong SAR van China", "中国香港特别行政区", "เขตปกครองพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน", "Sonderverwaltungsregion Hongkong", "Гонконг (САР)", "中華人民共和国香港特別行政区", "홍콩(중국 특별행정구)", "Đặc khu Hành chính Hồng Kông, Trung Quốc", "Hong Kong DAK Tiongkok", "RAE de Hong Kong (China)", "hong kong", "홍콩", "香港", "ฮ่องกง", "гонконг"] },
  HN: { name: "Honduras", aliases: ["洪都拉斯", "ฮอนดูรัส", "Гондурас", "ホンジュラス", "온두라스"] },
  HR: { name: "Kroatië", aliases: ["Croatia", "克罗地亚", "โครเอเชีย", "Kroatien", "Хорватия", "クロアチア", "크로아티아", "Kroasia", "Croacia"] },
  HT: { name: "Haïti", aliases: ["Haiti", "海地", "เฮติ", "Гаити", "ハイチ", "아이티", "Haití"] },
  HU: { name: "Hongarije", aliases: ["Hungary", "匈牙利", "ฮังการี", "Ungarn", "Венгрия", "ハンガリー", "헝가리", "Hungaria", "Hungría"] },
  ID: { name: "Indonesië", aliases: ["Indonesia", "印度尼西亚", "อินโดนีเซีย", "Indonesien", "Индонезия", "インドネシア", "인도네시아", "indonesia", "indonesie", "индонезия"] },
  IE: { name: "Ierland", aliases: ["Ireland", "爱尔兰", "ไอร์แลนด์", "Irland", "Ирландия", "アイルランド", "아일랜드", "Irlandia", "Irlanda", "ireland", "irland", "irlanda", "ирландия"] },
  IL: { name: "Israël", aliases: ["Israel", "以色列", "อิสราเอล", "Израиль", "イスラエル", "이스라엘", "israel", "израиль"] },
  IM: { name: "Isle of Man", aliases: ["马恩岛", "เกาะแมน", "о-в Мэн", "マン島", "맨섬", "Đảo Man", "Pulau Man", "Isla de Man"] },
  IN: { name: "India", aliases: ["印度", "อินเดีย", "Indien", "Индия", "インド", "인도", "Ấn Độ", "indië", "индия", "hindia"] },
  IO: { name: "Brits Indische Oceaanterritorium", aliases: ["British Indian Ocean Territory", "英属印度洋领地", "บริติชอินเดียนโอเชียนเทร์ริทอรี", "Britisches Territorium im Indischen Ozean", "Британская территория в Индийском океане", "英領インド洋地域", "영국령 인도양 지역", "Lãnh thổ Ấn Độ Dương thuộc Anh", "Wilayah Inggris di Samudra Hindia", "Territorio Británico del Océano Índico", "diego garcia", "british indian ocean"] },
  IQ: { name: "Irak", aliases: ["Iraq", "伊拉克", "อิรัก", "Ирак", "イラク", "이라크"] },
  IR: { name: "Iran", aliases: ["伊朗", "อิหร่าน", "Иран", "イラン", "이란", "Irán"] },
  IS: { name: "IJsland", aliases: ["Iceland", "冰岛", "ไอซ์แลนด์", "Island", "Исландия", "アイスランド", "아이슬란드", "Islandia"] },
  IT: { name: "Italië", aliases: ["Italy", "意大利", "อิตาลี", "Italien", "Италия", "イタリア", "이탈리아", "Italia", "italy", "italie", "italien", "italia", "италия"] },
  JE: { name: "Jersey", aliases: ["泽西岛", "เจอร์ซีย์", "Джерси", "ジャージー", "저지"] },
  JM: { name: "Jamaica", aliases: ["牙买加", "จาเมกา", "Jamaika", "Ямайка", "ジャマイカ", "자메이카"] },
  JO: { name: "Jordanië", aliases: ["Jordan", "约旦", "จอร์แดน", "Jordanien", "Иордания", "ヨルダン", "요르단", "Yordania", "Jordania"] },
  JP: { name: "Japan", aliases: ["日本", "ญี่ปุ่น", "Япония", "일본", "Nhật Bản", "Jepang", "Japón", "япония", "jepang", "japón", "nhật bản", "nhat ban"] },
  KE: { name: "Kenia", aliases: ["Kenya", "肯尼亚", "เคนยา", "Кения", "ケニア", "케냐"] },
  KG: { name: "Kirgizië", aliases: ["Kyrgyzstan", "吉尔吉斯斯坦", "คีร์กีซสถาน", "Kirgisistan", "Киргизия", "キルギス", "키르기스스탄", "Kirgizstan", "Kirguistán"] },
  KH: { name: "Cambodja", aliases: ["Cambodia", "柬埔寨", "กัมพูชา", "Kambodscha", "Камбоджа", "カンボジア", "캄보디아", "Campuchia", "Kamboja", "Camboya"] },
  KI: { name: "Kiribati", aliases: ["基里巴斯", "คิริบาส", "Кирибати", "キリバス", "키리바시"] },
  KM: { name: "Comoren", aliases: ["Comoros", "科摩罗", "คอโมโรส", "Komoren", "Коморы", "コモロ", "코모로", "Komoro", "Comoras"] },
  KN: { name: "Saint Kitts en Nevis", aliases: ["St. Kitts & Nevis", "圣基茨和尼维斯", "เซนต์คิตส์และเนวิส", "St. Kitts und Nevis", "Сент-Китс и Невис", "セントクリストファー・ネーヴィス", "세인트키츠 네비스", "St. Kitts và Nevis", "Saint Kitts dan Nevis", "San Cristóbal y Nieves"] },
  KP: { name: "Noord-Korea", aliases: ["North Korea", "朝鲜", "เกาหลีเหนือ", "Nordkorea", "КНДР", "北朝鮮", "북한", "Triều Tiên", "Korea Utara", "Corea del Norte", "north korea", "nordkorea", "corea del norte", "кндр"] },
  KR: { name: "Zuid-Korea", aliases: ["South Korea", "韩国", "เกาหลีใต้", "Südkorea", "Республика Корея", "韓国", "대한민국", "Hàn Quốc", "Korea Selatan", "Corea del Sur", "korea", "south korea", "südkorea", "sudkorea", "corea", "hàn quốc", "han quoc", "เกาหลี", "한국", "韓國", "корея"] },
  KW: { name: "Koeweit", aliases: ["Kuwait", "科威特", "คูเวต", "Кувейт", "クウェート", "쿠웨이트"] },
  KY: { name: "Kaaimaneilanden", aliases: ["Cayman Islands", "开曼群岛", "หมู่เกาะเคย์แมน", "Kaimaninseln", "о-ва Кайман", "ケイマン諸島", "케이맨 제도", "Quần đảo Cayman", "Kepulauan Cayman", "Islas Caimán"] },
  KZ: { name: "Kazachstan", aliases: ["Kazakhstan", "哈萨克斯坦", "คาซัคสถาน", "Kasachstan", "Казахстан", "カザフスタン", "카자흐스탄", "Kazajistán"] },
  LA: { name: "Laos", aliases: ["老挝", "ลาว", "Лаос", "ラオス", "라오스", "Lào"] },
  LB: { name: "Libanon", aliases: ["Lebanon", "黎巴嫩", "เลบานอน", "Ливан", "レバノン", "레바논", "Li-băng", "Líbano"] },
  LC: { name: "Saint Lucia", aliases: ["St. Lucia", "圣卢西亚", "เซนต์ลูเซีย", "Сент-Люсия", "セントルシア", "세인트루시아", "Santa Lucía"] },
  LK: { name: "Sri Lanka", aliases: ["斯里兰卡", "ศรีลังกา", "Шри-Ланка", "スリランカ", "스리랑카"] },
  LR: { name: "Liberia", aliases: ["利比里亚", "ไลบีเรีย", "Либерия", "リベリア", "라이베리아"] },
  LS: { name: "Lesotho", aliases: ["莱索托", "เลโซโท", "Лесото", "レソト", "레소토", "Lesoto"] },
  LT: { name: "Litouwen", aliases: ["Lithuania", "立陶宛", "ลิทัวเนีย", "Litauen", "Литва", "リトアニア", "리투아니아", "Litva", "Lituania"] },
  LU: { name: "Luxemburg", aliases: ["Luxembourg", "卢森堡", "ลักเซมเบิร์ก", "Люксембург", "ルクセンブルク", "룩셈부르크", "Luksemburg", "Luxemburgo"] },
  LV: { name: "Letland", aliases: ["Latvia", "拉脱维亚", "ลัตเวีย", "Lettland", "Латвия", "ラトビア", "라트비아", "Letonia"] },
  LY: { name: "Libië", aliases: ["Libya", "利比亚", "ลิเบีย", "Libyen", "Ливия", "リビア", "리비아", "Libia"] },
  MA: { name: "Marokko", aliases: ["Morocco", "摩洛哥", "โมร็อกโก", "Марокко", "モロッコ", "모로코", "Ma-rốc", "Maroko", "Marruecos"] },
  MD: { name: "Moldavië", aliases: ["Moldova", "摩尔多瓦", "มอลโดวา", "Republik Moldau", "Молдова", "モルドバ", "몰도바", "Moldavia"] },
  ME: { name: "Montenegro", aliases: ["黑山", "มอนเตเนโกร", "Черногория", "モンテネグロ", "몬테네그로"] },
  MF: { name: "Saint-Martin", aliases: ["St. Martin", "法属圣马丁", "เซนต์มาร์ติน", "Сен-Мартен", "サン・マルタン", "생마르탱", "Saint Martin", "San Martín"] },
  MG: { name: "Madagaskar", aliases: ["Madagascar", "马达加斯加", "มาดากัสการ์", "Мадагаскар", "マダガスカル", "마다가스카르"] },
  MH: { name: "Marshalleilanden", aliases: ["Marshall Islands", "马绍尔群岛", "หมู่เกาะมาร์แชลล์", "Marshallinseln", "Маршалловы о-ва", "マーシャル諸島", "마셜 제도", "Quần đảo Marshall", "Kepulauan Marshall", "Islas Marshall"] },
  MK: { name: "Noord-Macedonië", aliases: ["North Macedonia", "北马其顿", "มาซิโดเนียเหนือ", "Nordmazedonien", "Северная Македония", "北マケドニア", "북마케도니아", "Bắc Macedonia", "Makedonia Utara", "Macedonia del Norte"] },
  ML: { name: "Mali", aliases: ["马里", "มาลี", "Мали", "マリ", "말리"] },
  MM: { name: "Myanmar", aliases: ["Myanmar (Burma)", "Myanmar (Birma)", "缅甸", "เมียนมา (พม่า)", "Мьянма (Бирма)", "ミャンマー (ビルマ)", "미얀마", "Myanmar (Miến Điện)", "Myanmar (Birmania)", "burma", "ミャンマー", "เมียนมา", "мьянма"] },
  MN: { name: "Mongolië", aliases: ["Mongolia", "蒙古", "มองโกเลีย", "Mongolei", "Монголия", "モンゴル", "몽골", "Mông Cổ"] },
  MO: { name: "Macau", aliases: ["Macao SAR China", "Macau SAR van China", "中国澳门特别行政区", "เขตปกครองพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน", "Sonderverwaltungsregion Macau", "Макао (САР)", "中華人民共和国マカオ特別行政区", "마카오(중국 특별행정구)", "Đặc khu Hành chính Macao, Trung Quốc", "Makau DAK Tiongkok", "RAE de Macao (China)", "macao", "마카오", "マカオ", "澳门", "มาเก๊า", "макао"] },
  MP: { name: "Noordelijke Marianen", aliases: ["Northern Mariana Islands", "北马里亚纳群岛", "หมู่เกาะนอร์เทิร์นมาเรียนา", "Nördliche Marianen", "Северные Марианские о-ва", "北マリアナ諸島", "북마리아나제도", "Quần đảo Bắc Mariana", "Kepulauan Mariana Utara", "Islas Marianas del Norte", "saipan", "northern mariana"] },
  MQ: { name: "Martinique", aliases: ["马提尼克", "มาร์ตินีก", "Мартиника", "マルティニーク", "마르티니크", "Martinik", "Martinica"] },
  MR: { name: "Mauritanië", aliases: ["Mauritania", "毛里塔尼亚", "มอริเตเนีย", "Mauretanien", "Мавритания", "モーリタニア", "모리타니"] },
  MS: { name: "Montserrat", aliases: ["蒙特塞拉特", "มอนต์เซอร์รัต", "Монтсеррат", "モントセラト", "몬트세라트"] },
  MT: { name: "Malta", aliases: ["马耳他", "มอลตา", "Мальта", "マルタ", "몰타"] },
  MU: { name: "Mauritius", aliases: ["毛里求斯", "มอริเชียส", "Маврикий", "モーリシャス", "모리셔스", "Mauricio"] },
  MV: { name: "Maldiven", aliases: ["Maldives", "马尔代夫", "มัลดีฟส์", "Malediven", "Мальдивы", "モルディブ", "몰디브", "Maladewa", "Maldivas"] },
  MW: { name: "Malawi", aliases: ["马拉维", "มาลาวี", "Малави", "マラウイ", "말라위", "Malaui"] },
  MX: { name: "Mexico", aliases: ["墨西哥", "เม็กซิโก", "Mexiko", "Мексика", "メキシコ", "멕시코", "Meksiko", "México", "méxico", "mexiko", "мексика"] },
  MY: { name: "Maleisië", aliases: ["Malaysia", "马来西亚", "มาเลเซีย", "Малайзия", "マレーシア", "말레이시아", "Malasia", "malaysia", "maleisie", "малайзия"] },
  MZ: { name: "Mozambique", aliases: ["莫桑比克", "โมซัมบิก", "Mosambik", "Мозамбик", "モザンビーク", "모잠비크", "Mozambik"] },
  NA: { name: "Namibië", aliases: ["Namibia", "纳米比亚", "นามิเบีย", "Намибия", "ナミビア", "나미비아"] },
  NC: { name: "Nieuw-Caledonië", aliases: ["New Caledonia", "新喀里多尼亚", "นิวแคลิโดเนีย", "Neukaledonien", "Новая Каледония", "ニューカレドニア", "뉴칼레도니아", "Kaledonia Baru", "Nueva Caledonia", "new caledonia", "neukaledonien", "nueva caledonia"] },
  NE: { name: "Niger", aliases: ["尼日尔", "ไนเจอร์", "Нигер", "ニジェール", "니제르", "Níger"] },
  NF: { name: "Norfolk", aliases: ["Norfolk Island", "诺福克岛", "เกาะนอร์ฟอล์ก", "Norfolkinsel", "о-в Норфолк", "ノーフォーク島", "노퍽섬", "Đảo Norfolk", "Kepulauan Norfolk", "Isla Norfolk"] },
  NG: { name: "Nigeria", aliases: ["尼日利亚", "ไนจีเรีย", "Нигерия", "ナイジェリア", "나이지리아"] },
  NI: { name: "Nicaragua", aliases: ["尼加拉瓜", "นิการากัว", "Никарагуа", "ニカラグア", "니카라과", "Nikaragua"] },
  NL: { name: "Nederland", aliases: ["Netherlands", "荷兰", "เนเธอร์แลนด์", "Niederlande", "Нидерланды", "オランダ", "네덜란드", "Hà Lan", "Belanda", "Países Bajos", "holland", "netherlands"] },
  NO: { name: "Noorwegen", aliases: ["Norway", "挪威", "นอร์เวย์", "Norwegen", "Норвегия", "ノルウェー", "노르웨이", "Na Uy", "Norwegia", "Noruega"] },
  NP: { name: "Nepal", aliases: ["尼泊尔", "เนปาล", "Непал", "ネパール", "네팔"] },
  NR: { name: "Nauru", aliases: ["瑙鲁", "นาอูรู", "Науру", "ナウル", "나우루"] },
  NU: { name: "Niue", aliases: ["纽埃", "นีอูเอ", "Ниуэ", "ニウエ", "니우에"] },
  NZ: { name: "Nieuw-Zeeland", aliases: ["New Zealand", "新西兰", "นิวซีแลนด์", "Neuseeland", "Новая Зеландия", "ニュージーランド", "뉴질랜드", "Selandia Baru", "Nueva Zelanda", "new zealand", "neuseeland", "nueva zelanda", "новая зеландия"] },
  OM: { name: "Oman", aliases: ["阿曼", "โอมาน", "Оман", "オマーン", "오만", "Omán"] },
  PA: { name: "Panama", aliases: ["巴拿马", "ปานามา", "Панама", "パナマ", "파나마", "Panamá"] },
  PE: { name: "Peru", aliases: ["秘鲁", "เปรู", "Перу", "ペルー", "페루", "Perú"] },
  PF: { name: "Frans-Polynesië", aliases: ["French Polynesia", "法属波利尼西亚", "เฟรนช์โปลินีเซีย", "Französisch-Polynesien", "Французская Полинезия", "仏領ポリネシア", "프랑스령 폴리네시아", "Polynesia thuộc Pháp", "Polinesia Prancis", "Polinesia Francesa", "tahiti", "french polynesia", "polinesia francesa"] },
  PG: { name: "Papoea-Nieuw-Guinea", aliases: ["Papua New Guinea", "巴布亚新几内亚", "ปาปัวนิวกินี", "Papua-Neuguinea", "Папуа — Новая Гвинея", "パプアニューギニア", "파푸아뉴기니", "Papua Nugini", "Papúa Nueva Guinea", "papua new guinea", "papua-neuguinea", "papúa nueva guinea", "papua"] },
  PH: { name: "Filipijnen", aliases: ["Philippines", "菲律宾", "ฟิลิปปินส์", "Philippinen", "Филиппины", "フィリピン", "필리핀", "Filipina", "Filipinas", "philippines", "filipinas", "филиппины"] },
  PK: { name: "Pakistan", aliases: ["巴基斯坦", "ปากีสถาน", "Пакистан", "パキスタン", "파키스탄", "Pakistán"] },
  PL: { name: "Polen", aliases: ["Poland", "波兰", "โปแลนด์", "Польша", "ポーランド", "폴란드", "Ba Lan", "Polandia", "Polonia", "poland", "polonia", "polandia", "польша"] },
  PM: { name: "Saint-Pierre en Miquelon", aliases: ["St. Pierre & Miquelon", "圣皮埃尔和密克隆群岛", "แซงปีแยร์และมีเกอลง", "St. Pierre und Miquelon", "Сен-Пьер и Микелон", "サンピエール島・ミクロン島", "생피에르 미클롱", "Saint Pierre và Miquelon", "Saint Pierre dan Miquelon", "San Pedro y Miquelón"] },
  PR: { name: "Puerto Rico", aliases: ["波多黎各", "เปอร์โตริโก", "Пуэрто-Рико", "プエルトリコ", "푸에르토리코", "Puerto Riko"] },
  PT: { name: "Portugal", aliases: ["葡萄牙", "โปรตุเกส", "Португалия", "ポルトガル", "포르투갈", "Bồ Đào Nha"] },
  PW: { name: "Palau", aliases: ["帕劳", "ปาเลา", "Палау", "パラオ", "팔라우", "Palaos"] },
  PY: { name: "Paraguay", aliases: ["巴拉圭", "ปารากวัย", "Парагвай", "パラグアイ", "파라과이"] },
  QA: { name: "Qatar", aliases: ["卡塔尔", "กาตาร์", "Katar", "Катар", "カタール", "카타르", "Catar"] },
  RE: { name: "Réunion", aliases: ["留尼汪", "เรอูนียง", "Реюньон", "レユニオン", "레위니옹", "Reunión"] },
  RO: { name: "Roemenië", aliases: ["Romania", "罗马尼亚", "โรมาเนีย", "Rumänien", "Румыния", "ルーマニア", "루마니아", "Rumania", "Rumanía"] },
  RS: { name: "Servië", aliases: ["Serbia", "塞尔维亚", "เซอร์เบีย", "Serbien", "Сербия", "セルビア", "세르비아"] },
  RU: { name: "Rusland", aliases: ["Russia", "俄罗斯", "รัสเซีย", "Russland", "Россия", "ロシア", "러시아", "Nga", "Rusia", "russia", "россия"] },
  RW: { name: "Rwanda", aliases: ["卢旺达", "รวันดา", "Ruanda", "Руанда", "ルワンダ", "르완다"] },
  SA: { name: "Saoedi-Arabië", aliases: ["Saudi Arabia", "沙特阿拉伯", "ซาอุดีอาระเบีย", "Saudi-Arabien", "Саудовская Аравия", "サウジアラビア", "사우디아라비아", "Ả Rập Xê-út", "Arab Saudi", "Arabia Saudí", "saudi", "saudi arabia", "saoedi"] },
  SB: { name: "Salomonseilanden", aliases: ["Solomon Islands", "所罗门群岛", "หมู่เกาะโซโลมอน", "Salomonen", "Соломоновы о-ва", "ソロモン諸島", "솔로몬 제도", "Quần đảo Solomon", "Kepulauan Solomon", "Islas Salomón"] },
  SC: { name: "Seychellen", aliases: ["Seychelles", "塞舌尔", "เซเชลส์", "Сейшельские о-ва", "セーシェル", "세이셸"] },
  SD: { name: "Soedan", aliases: ["Sudan", "苏丹", "ซูดาน", "Судан", "スーダン", "수단", "Sudán"] },
  SE: { name: "Zweden", aliases: ["Sweden", "瑞典", "สวีเดน", "Schweden", "Швеция", "スウェーデン", "스웨덴", "Thụy Điển", "Swedia", "Suecia"] },
  SG: { name: "Singapore", aliases: ["新加坡", "สิงคโปร์", "Singapur", "Сингапур", "シンガポール", "싱가포르", "Singapura", "singapura", "сингапур"] },
  SH: { name: "Sint-Helena", aliases: ["St. Helena", "圣赫勒拿", "เซนต์เฮเลนา", "о-в Св. Елены", "セントヘレナ", "세인트헬레나", "Saint Helena", "Santa Elena"] },
  SI: { name: "Slovenië", aliases: ["Slovenia", "斯洛文尼亚", "สโลวีเนีย", "Slowenien", "Словения", "スロベニア", "슬로베니아", "Eslovenia"] },
  SK: { name: "Slowakije", aliases: ["Slovakia", "斯洛伐克", "สโลวะเกีย", "Slowakei", "Словакия", "スロバキア", "슬로바키아", "Eslovaquia"] },
  SL: { name: "Sierra Leone", aliases: ["塞拉利昂", "เซียร์ราลีโอน", "Сьерра-Леоне", "シエラレオネ", "시에라리온", "Sierra Leona"] },
  SN: { name: "Senegal", aliases: ["塞内加尔", "เซเนกัล", "Сенегал", "セネガル", "세네갈"] },
  SO: { name: "Somalië", aliases: ["Somalia", "索马里", "โซมาเลีย", "Сомали", "ソマリア", "소말리아"] },
  SR: { name: "Suriname", aliases: ["苏里南", "ซูรินาเม", "Суринам", "スリナム", "수리남", "Surinam"] },
  SS: { name: "Zuid-Soedan", aliases: ["South Sudan", "南苏丹", "ซูดานใต้", "Südsudan", "Южный Судан", "南スーダン", "남수단", "Nam Sudan", "Sudan Selatan", "Sudán del Sur", "south sudan", "südsudan", "sudán del sur"] },
  ST: { name: "Sao Tomé en Principe", aliases: ["São Tomé & Príncipe", "圣多美和普林西比", "เซาตูเมและปรินซิปี", "São Tomé und Príncipe", "Сан-Томе и Принсипи", "サントメ・プリンシペ", "상투메 프린시페", "São Tomé và Príncipe", "Sao Tome dan Principe", "Santo Tomé y Príncipe"] },
  SV: { name: "El Salvador", aliases: ["萨尔瓦多", "เอลซัลวาดอร์", "Сальвадор", "エルサルバドル", "엘살바도르"] },
  SX: { name: "Sint-Maarten", aliases: ["Sint Maarten", "荷属圣马丁", "ซินต์มาร์เทน", "Синт-Мартен", "シント・マールテン", "신트마르턴", "sint maarten", "st maarten", "saint martin"] },
  SY: { name: "Syrië", aliases: ["Syria", "叙利亚", "ซีเรีย", "Syrien", "Сирия", "シリア", "시리아", "Suriah", "Siria"] },
  SZ: { name: "Eswatini", aliases: ["斯威士兰", "เอสวาตีนี", "Эсватини", "エスワティニ", "에스와티니", "Esuatini"] },
  TC: { name: "Turks- en Caicoseilanden", aliases: ["Turks & Caicos Islands", "特克斯和凯科斯群岛", "หมู่เกาะเติกส์และหมู่เกาะเคคอส", "Turks- und Caicosinseln", "Тёркс и Кайкос", "タークス・カイコス諸島", "터크스 케이커스 제도", "Quần đảo Turks và Caicos", "Kepulauan Turks dan Caicos", "Islas Turcas y Caicos"] },
  TD: { name: "Tsjaad", aliases: ["Chad", "乍得", "ชาด", "Tschad", "Чад", "チャド", "차드"] },
  TG: { name: "Togo", aliases: ["多哥", "โตโก", "Того", "トーゴ", "토고"] },
  TH: { name: "Thailand", aliases: ["泰国", "ไทย", "Таиланд", "タイ", "태국", "Thái Lan", "Tailandia", "тайланд", "tailandia"] },
  TJ: { name: "Tadzjikistan", aliases: ["Tajikistan", "塔吉克斯坦", "ทาจิกิสถาน", "Tadschikistan", "Таджикистан", "タジキスタン", "타지키스탄", "Tayikistán"] },
  TL: { name: "Oost-Timor", aliases: ["Timor-Leste", "东帝汶", "ติมอร์-เลสเต", "Восточный Тимор", "東ティモール", "동티모르", "Timor Leste", "timor-leste", "east timor", "osttimor", "timor oriental"] },
  TM: { name: "Turkmenistan", aliases: ["土库曼斯坦", "เติร์กเมนิสถาน", "Туркменистан", "トルクメニスタン", "투르크메니스탄", "Turkmenistán"] },
  TN: { name: "Tunesië", aliases: ["Tunisia", "突尼斯", "ตูนิเซีย", "Tunesien", "Тунис", "チュニジア", "튀니지", "Túnez"] },
  TO: { name: "Tonga", aliases: ["汤加", "ตองกา", "Тонга", "トンガ", "통가"] },
  TR: { name: "Turkije", aliases: ["Türkiye", "土耳其", "ตุรกี", "Türkei", "Турция", "トルコ", "튀르키예", "Thổ Nhĩ Kỳ", "Turki", "Turquía", "turkey", "turkiye", "türkei", "turquía", "터키", "турция"] },
  TT: { name: "Trinidad en Tobago", aliases: ["Trinidad & Tobago", "特立尼达和多巴哥", "ตรินิแดดและโตเบโก", "Trinidad und Tobago", "Тринидад и Тобаго", "トリニダード・トバゴ", "트리니다드 토바고", "Trinidad và Tobago", "Trinidad dan Tobago", "Trinidad y Tobago", "trinidad"] },
  TV: { name: "Tuvalu", aliases: ["图瓦卢", "ตูวาลู", "Тувалу", "ツバル", "투발루"] },
  TW: { name: "Taiwan", aliases: ["台湾", "ไต้หวัน", "Тайвань", "대만", "Đài Loan", "Taiwán", "台灣", "臺灣", "타이완", "đài loan", "dai loan", "тайвань", "taiwán", "formosa"] },
  TZ: { name: "Tanzania", aliases: ["坦桑尼亚", "แทนซาเนีย", "Tansania", "Танзания", "タンザニア", "탄자니아"] },
  UA: { name: "Oekraïne", aliases: ["Ukraine", "乌克兰", "ยูเครน", "Украина", "ウクライナ", "우크라이나", "Ukraina", "Ucrania"] },
  UG: { name: "Oeganda", aliases: ["Uganda", "乌干达", "ยูกันดา", "Уганда", "ウガンダ", "우간다"] },
  UM: { name: "Kleine afgelegen eilanden van de Verenigde Staten", aliases: ["U.S. Outlying Islands", "美国本土外小岛屿", "หมู่เกาะรอบนอกของสหรัฐอเมริกา", "Amerikanische Überseeinseln", "Внешние малые о-ва (США)", "合衆国領有小離島", "미국령 해외 제도", "Các tiểu đảo xa của Hoa Kỳ", "Kepulauan Terluar AS", "Islas menores alejadas de EE. UU.", "wake", "midway", "us minor outlying"] },
  US: { name: "Verenigde Staten", aliases: ["United States", "美国", "สหรัฐอเมริกา", "Vereinigte Staaten", "Соединенные Штаты", "アメリカ合衆国", "미국", "Hoa Kỳ", "Amerika Serikat", "Estados Unidos", "usa", "america", "united states", "amerika", "アメリカ", "สหรัฐ", "сша", "amerika serikat", "estados unidos"] },
  UY: { name: "Uruguay", aliases: ["乌拉圭", "อุรุกวัย", "Уругвай", "ウルグアイ", "우루과이"] },
  UZ: { name: "Oezbekistan", aliases: ["Uzbekistan", "乌兹别克斯坦", "อุซเบกิสถาน", "Usbekistan", "Узбекистан", "ウズベキスタン", "우즈베키스탄", "Uzbekistán"] },
  VC: { name: "Saint Vincent en de Grenadines", aliases: ["St. Vincent & Grenadines", "圣文森特和格林纳丁斯", "เซนต์วินเซนต์และเกรนาดีนส์", "St. Vincent und die Grenadinen", "Сент-Винсент и Гренадины", "セントビンセント及びグレナディーン諸島", "세인트빈센트그레나딘", "St. Vincent và Grenadines", "Saint Vincent dan Grenadine", "San Vicente y las Granadinas"] },
  VE: { name: "Venezuela", aliases: ["委内瑞拉", "เวเนซุเอลา", "Венесуэла", "ベネズエラ", "베네수엘라"] },
  VG: { name: "Britse Maagdeneilanden", aliases: ["British Virgin Islands", "英属维尔京群岛", "หมู่เกาะบริติชเวอร์จิน", "Britische Jungferninseln", "Виргинские о-ва (Великобритания)", "英領ヴァージン諸島", "영국령 버진아일랜드", "Quần đảo Virgin thuộc Anh", "Kepulauan Virgin Britania Raya", "Islas Vírgenes Británicas"] },
  VI: { name: "Amerikaanse Maagdeneilanden", aliases: ["U.S. Virgin Islands", "美属维尔京群岛", "หมู่เกาะเวอร์จินของสหรัฐอเมริกา", "Amerikanische Jungferninseln", "Виргинские о-ва (США)", "米領ヴァージン諸島", "미국령 버진아일랜드", "Quần đảo Virgin thuộc Hoa Kỳ", "Kepulauan Virgin Amerika Serikat", "Islas Vírgenes de EE. UU."] },
  VN: { name: "Vietnam", aliases: ["越南", "เวียดนาม", "Вьетнам", "ベトナム", "베트남", "Việt Nam", "việt nam", "viet nam", "вьетнам"] },
  VU: { name: "Vanuatu", aliases: ["瓦努阿图", "วานูอาตู", "Вануату", "バヌアツ", "바누아투"] },
  WF: { name: "Wallis en Futuna", aliases: ["Wallis & Futuna", "瓦利斯和富图纳", "วาลลิสและฟุตูนา", "Wallis und Futuna", "Уоллис и Футуна", "ウォリス・フツナ", "왈리스-푸투나 제도", "Wallis và Futuna", "Kepulauan Wallis dan Futuna", "Wallis y Futuna"] },
  WS: { name: "Samoa", aliases: ["萨摩亚", "ซามัว", "Самоа", "サモア", "사모아"] },
  XK: { name: "Kosovo", aliases: ["科索沃", "โคโซโว", "Косово", "コソボ", "코소보", "косово"] },
  YE: { name: "Jemen", aliases: ["Yemen", "也门", "เยเมน", "Йемен", "イエメン", "예멘", "Yaman"] },
  YT: { name: "Mayotte", aliases: ["马约特", "มายอต", "Майотта", "マヨット", "마요트"] },
  ZA: { name: "Zuid-Afrika", aliases: ["South Africa", "南非", "แอฟริกาใต้", "Südafrika", "Южно-Африканская Республика", "南アフリカ", "남아프리카", "Nam Phi", "Afrika Selatan", "Sudáfrica", "south africa", "südafrika", "sudáfrica", "юар"] },
  ZM: { name: "Zambia", aliases: ["赞比亚", "แซมเบีย", "Sambia", "Замбия", "ザンビア", "잠비아"] },
  ZW: { name: "Zimbabwe", aliases: ["津巴布韦", "ซิมบับเว", "Simbabwe", "Зимбабве", "ジンバブエ", "짐바브웨", "Zimbabue"] },
};
