import { PetRule } from '../../types/pet';

const VERIFIED = '2026-08-01';

const STD_REQ = [
  'Health certificate (max 10 days old)',
  'Approved IATA crate',
  'Rabies vaccination',
  'Microchip (ISO 11784/11785)',
];

const PREBOOK = 'Pre-register with the airline (not via this app)';
const LIMITED = 'Limited spaces per flight — book as early as possible';
const ASSIST_ONLY = 'Accredited assistance animals may be accepted separately — contact the airline';

function extra(
  airlineIata: string,
  rule: Omit<PetRule, 'airlineIata' | 'lastVerified'>,
): PetRule {
  return { airlineIata, lastVerified: VERIFIED, ...rule };
}

export type CountryPetEntry = {
  countryCode: string;
  microchipRequired: boolean;
  vaccinesRequired: string[];
  quarantineDays: number;
};

/** Destination-country import defaults. Airlines may still add extra rules. */
export const COUNTRY_PET_RULES: CountryPetEntry[] = [
  { countryCode: 'TH', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'SG', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'MY', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'ID', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'VN', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'PH', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'JP', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 180 },
  { countryCode: 'KR', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'CN', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 7 },
  { countryCode: 'HK', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'TW', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'IN', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'AU', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 10 },
  { countryCode: 'NZ', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 10 },
  { countryCode: 'US', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'CA', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'GB', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'NL', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'DE', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'FR', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'ES', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'IT', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'AE', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'QA', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'ZA', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'BR', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
  { countryCode: 'MX', microchipRequired: true, vaccinesRequired: ['Rabies'], quarantineDays: 0 },
];

function withImportDefaults(rule: PetRule): PetRule {
  return {
    ...rule,
    microchipRequired: rule.microchipRequired ?? true,
    vaccinesRequired: rule.vaccinesRequired ?? ['Rabies'],
    quarantineDays: rule.quarantineDays ?? 0,
  };
}

const NO_PETS = (
  iata: string,
  name: string,
  sourceUrl: string,
  extraWarnings: string[] = [],
): PetRule => extra(iata, {
  animalTypes: ['dog_small', 'dog_large', 'cat', 'rabbit', 'bird', 'reptile', 'other'],
  cabinAllowed: false,
  holdAllowed: false,
  brachycephalicBanned: false,
  requirements: [],
  warnings: [
    `${name} does not accept pets in the cabin or hold`,
    ASSIST_ONLY,
    ...extraWarnings,
  ],
  sourceUrl,
});

const EXTRA_RULES: PetRule[] = [
  // --- Europe ---
  extra('BA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 6,
    maxWeightHold: 75,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Cabin pets only on selected routes; pet + carrier typically up to 6 kg',
      'Brachycephalic breeds not accepted in the hold',
      LIMITED,
    ],
    sourceUrl: 'https://www.britishairways.com/en-gb/information/travel-assistance/travelling-with-pets',
  }),
  extra('VS', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 75,
    brachycephalicBanned: true,
    requirements: [
      'Health certificate (max 10 days old)',
      'IATA-approved carrier',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'Pre-register with Virgin Atlantic Cargo',
    ],
    warnings: [
      'No pets allowed in cabin on Virgin Atlantic',
      'Snub-nosed breeds not accepted in hold',
      'Must book via Virgin Atlantic Cargo separately',
      'Not available on all routes',
    ],
    sourceUrl: 'https://www.virginatlantic.com/en/gb/travel-information/pets.html',
  }),
  extra('AF', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 75,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Cabin only up to 8 kg including carrier',
      'Snub-nosed breeds restricted or banned in the hold, especially in warm months',
      LIMITED,
    ],
    sourceUrl: 'https://wwws.airfrance.nl/en/information/prepare/special-assistance/animals',
  }),
  extra('IB', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 45,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', LIMITED],
    sourceUrl: 'https://www.iberia.com/nl/pets/',
  }),
  extra('AZ', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 10,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin weight limits vary by aircraft — confirm with ITA Airways', LIMITED],
    sourceUrl: 'https://www.ita-airways.com/en_en/fly-ita/prepare-to-fly/pets.html',
  }),
  extra('SK', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', LIMITED],
    sourceUrl: 'https://www.flysas.com/en/travel-info/special-assistance/travelling-with-pets/',
  }),
  extra('OS', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Cabin only up to 8 kg including crate',
      'Brachycephalic breeds not allowed in the hold in summer',
      LIMITED,
    ],
    sourceUrl: 'https://www.austrian.com/nl/en/travelling-with-animals',
  }),
  extra('LX', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Cabin only up to 8 kg including crate',
      'Brachycephalic breeds not accepted as checked pets',
      LIMITED,
    ],
    sourceUrl: 'https://www.swiss.com/nl/en/prepare/special-assistance/animals',
  }),
  extra('TP', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', LIMITED],
    sourceUrl: 'https://www.flytap.com/en-nl/travelling-with-animals',
  }),
  NO_PETS('VY', 'Vueling', 'https://www.vueling.com/en/help/travelling-with-pets-or-animals'),
  NO_PETS('FR', 'Ryanair', 'https://www.ryanair.com/gb/en/useful-info/help-centre/terms-and-conditions', [
    'Ryanair does not accept pets except accredited assistance dogs',
  ]),
  NO_PETS('U2', 'easyJet', 'https://www.easyjet.com/en/help/boarding-and-flying/special-assistance'),
  extra('TK', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Cabin only up to 8 kg including carrier',
      'Brachycephalic breeds not accepted in the hold',
      LIMITED,
    ],
    sourceUrl: 'https://www.turkishairlines.com/en-int/any-questions/how-can-i-travel-with-my-pet/',
  }),
  extra('HV', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Transavia typically allows small pets in the cabin only', LIMITED],
    sourceUrl: 'https://www.transavia.com/en-EU/faq/pets/',
  }),
  extra('PC', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Pegasus cabin pets only on selected routes', LIMITED],
    sourceUrl: 'https://www.flypgs.com/en/travel-services/special-passengers/pets',
  }),
  extra('DY', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Norwegian accepts small cabin pets on some routes only', 'Not available on all aircraft'],
    sourceUrl: 'https://www.norwegian.com/en/travel-info/baggage/special-baggage/pets/',
  }),
  NO_PETS('W6', 'Wizz Air', 'https://www.wizzair.com/en-gb/information-and-services/booking-information/special-assistance'),
  extra('SN', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including crate', 'Brachycephalic breeds restricted in the hold', LIMITED],
    sourceUrl: 'https://www.brusselsairlines.com/en-be/practical-information/travel-info/travelling-with-pets',
  }),
  extra('LO', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', LIMITED],
    sourceUrl: 'https://www.lot.com/us/en/travel/special-assistance/pets',
  }),
  extra('OK', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Czech Airlines / Smartwings group rules can vary — confirm at booking', LIMITED],
    sourceUrl: 'https://www.csa.cz/cz-en/travel-information/special-assistance/travelling-with-pets/',
  }),
  extra('BT', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['airBaltic cabin pets only on selected routes', LIMITED],
    sourceUrl: 'https://www.airbaltic.com/en/travelling-with-pets',
  }),
  extra('AY', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Cabin only up to 8 kg including carrier',
      'Brachycephalic breeds not accepted in the hold',
      LIMITED,
    ],
    sourceUrl: 'https://www.finnair.com/en/information-services/special-assistance/travelling-with-pets',
  }),
  extra('EI', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Aer Lingus cabin/hold availability depends on aircraft and route', LIMITED],
    sourceUrl: 'https://www.aerlingus.com/travel-information/special-assistance/travelling-with-pets/',
  }),
  extra('VK', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: false,
    requirements: [],
    warnings: [
      'Viking Air is not a major scheduled carrier — verify the operating airline on your ticket',
      ASSIST_ONLY,
    ],
    sourceUrl: 'https://www.iata.org/en/programs/cargo/live-animals/',
  }),
  extra('A3', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', LIMITED],
    sourceUrl: 'https://en.aegeanair.com/travel-info/special-assistance/travelling-with-pets/',
  }),
  extra('OA', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Olympic Air typically allows small cabin pets on domestic Greek routes', LIMITED],
    sourceUrl: 'https://www.olympicair.com/en/TravelInformation/SpecialAssistance/Pets',
  }),
  extra('RO', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', LIMITED],
    sourceUrl: 'https://www.tarom.ro/en/passenger-information/special-assistance/travelling-with-pets',
  }),
  extra('FB', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [LIMITED],
    sourceUrl: 'https://www.air.bg/en/travel-info/special-assistance/pets',
  }),
  extra('JU', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [LIMITED],
    sourceUrl: 'https://www.airserbia.com/en/information/special-assistance/pets',
  }),
  extra('OU', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [LIMITED],
    sourceUrl: 'https://www.croatiaairlines.com/Travel-info/Special-assistance/Pets',
  }),
  extra('EW', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Eurowings cabin pets typically under 8 kg including carrier', LIMITED],
    sourceUrl: 'https://www.eurowings.com/en/service/special-assistance/travelling-with-pets.html',
  }),
  extra('DE', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Cabin only up to 8 kg including carrier', 'Brachycephalic breeds often refused in the hold', LIMITED],
    sourceUrl: 'https://www.condor.com/eu/prepare/special-assistance/animals.jsp',
  }),
  extra('X3', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['TUI fly Germany: small cabin pets on selected leisure routes only'],
    sourceUrl: 'https://www.tui.com/flight/service/animals/',
  }),
  extra('OR', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 6,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['TUI fly Netherlands: small cabin pets on selected routes only'],
    sourceUrl: 'https://www.tui.nl/vliegtickets/huisdieren/',
  }),
  extra('PS', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Ukraine International operations remain limited — confirm the flight is operating',
      LIMITED,
    ],
    sourceUrl: 'https://www.flyuia.com/eng/information/special-assistance/animals.html',
  }),
  extra('SU', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 50,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Many international routes currently suspended due to sanctions (2022-present). Verify current route availability before booking.',
      'Cabin typically up to 8 kg including carrier',
    ],
    sourceUrl: 'https://www.aeroflot.ru/xx-en/information/legal/animals',
  }),

  // --- Middle East ---
  extra('MS', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['EgyptAir generally does not accept pets in the cabin', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://www.egyptair.com/en/fly/special-services/Pages/pets.aspx',
  }),
  extra('GF', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Gulf Air pets typically travel as manifested cargo / hold only'],
    sourceUrl: 'https://www.gulfair.com/en/information/special-assistance/travelling-with-pets',
  }),
  extra('WY', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Oman Air: hold / cargo pets only', 'Brachycephalic breeds often not accepted'],
    sourceUrl: 'https://www.omanair.com/en/plan/special-assistance/travelling-pets',
  }),
  extra('ME', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 5,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['MEA cabin pets only if very small and pre-approved', LIMITED],
    sourceUrl: 'https://www.mea.com.lb/english/plan-and-book/special-services/pets',
  }),
  NO_PETS('FZ', 'flydubai', 'https://www.flydubai.com/en/plan/special-assistance'),
  NO_PETS('G9', 'Air Arabia', 'https://www.airarabia.com/en/conditions-carriage'),

  // --- Southeast Asia ---
  extra('MH', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'No pets in the cabin on Malaysia Airlines',
      'Brachycephalic breeds not allowed',
      'Malaysia import permits required for inbound pets',
    ],
    sourceUrl: 'https://www.malaysiaairlines.com/hq/en/plan/special-assistance/travelling-with-pets.html',
  }),
  extra('GA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Garuda: hold only; cabin pets not offered on most flights', 'Indonesia import rules are strict'],
    sourceUrl: 'https://www.garuda-indonesia.com/other-countries/en/garuda-indonesia-experience/on-ground/special-assistance',
  }),
  extra('PR', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 7,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Philippine Airlines cabin pets only on selected domestic flights', LIMITED],
    sourceUrl: 'https://www.philippineairlines.com/en/travel-information/special-assistance/pets',
  }),
  extra('VN', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Vietnam Airlines: hold only on most routes', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://www.vietnamairlines.com/us/en/travel-information/special-assistance/pets',
  }),
  NO_PETS('AK', 'AirAsia (Malaysia)', 'https://www.airasia.com/aa/about-us/en/gb/conditions-of-carriage.html'),
  NO_PETS('QZ', 'AirAsia Indonesia', 'https://www.airasia.com/aa/about-us/en/gb/conditions-of-carriage.html'),
  NO_PETS('SL', 'Thai Lion Air', 'https://www.lionairthai.com/en/Terms-and-Conditions'),
  NO_PETS('VZ', 'Thai Vietjet', 'https://www.vietjetair.com/en/pages/condition-of-carriage-1602060054550'),
  NO_PETS('PG', 'Bangkok Airways', 'https://www.bangkokair.com/terms-and-conditions'),
  NO_PETS('DD', 'Nok Air', 'https://www.nokair.com/en/terms-and-conditions'),
  extra('QV', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: false,
    requirements: [],
    warnings: ['Lao Airlines generally does not accept pets on passenger flights', ASSIST_ONLY],
    sourceUrl: 'https://www.laoairlines.com/',
  }),
  extra('UB', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 20,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Myanmar National Airlines: cargo/hold only if accepted — confirm before booking'],
    sourceUrl: 'https://www.flymna.com/',
  }),
  extra('BI', {
    animalTypes: ['cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Royal Brunei does not accept dogs on most services',
      'Cats may be accepted as cargo only — confirm with the airline',
    ],
    sourceUrl: 'https://www.flyroyalbrunei.com/brunei/en/information/special-assistance/',
  }),

  // --- Northeast Asia ---
  extra('CX', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['No pets in the cabin on Cathay Pacific', 'Brachycephalic breeds not accepted'],
    sourceUrl: 'https://www.cathaypacific.com/cx/en_HK/travel-information/special-assistance/travelling-with-pets.html',
  }),
  extra('JL', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Japan Airlines: pets travel as checked baggage / cargo, not in the cabin',
      'Brachycephalic breeds restricted',
      'Japan import quarantine rules apply',
    ],
    sourceUrl: 'https://www.jal.co.jp/en/inter/board/pet/',
  }),
  extra('NH', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['ANA: hold / cargo pets only', 'Brachycephalic breeds often not accepted', 'Japan quarantine applies'],
    sourceUrl: 'https://www.ana.co.jp/en/us/travel-information/special-assistance/pets/',
  }),
  extra('KE', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Korean Air: hold only on passenger flights', 'Brachycephalic breeds not accepted'],
    sourceUrl: 'https://www.koreanair.com/contents/plan-your-travel/special-assistance/pets',
  }),
  extra('OZ', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Asiana: hold only', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://flyasiana.com/C/US/EN/contents/pets',
  }),
  extra('CA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: true,
    requirements: [...STD_REQ],
    warnings: [
      'Air China is very strict — pets are often not accepted on passenger flights',
      'If accepted at all, it is usually via cargo with lengthy permits',
      'Confirm directly with Air China Cargo before booking',
    ],
    sourceUrl: 'https://www.airchina.com.cn/en/info/service/special_service/pets.shtml',
  }),
  extra('MU', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: true,
    requirements: [...STD_REQ],
    warnings: [
      'China Eastern generally does not accept pets in cabin or as checked baggage on passenger flights',
      'Cargo-only with import permits if available',
    ],
    sourceUrl: 'https://www.ceair.com/newCMS/ceair/en/content/en_Header/EN_HEADER_MENU/201904/t20190416_4545.html',
  }),
  extra('CZ', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: true,
    requirements: [...STD_REQ],
    warnings: [
      'China Southern is very strict — passenger-flight pets are usually not offered',
      'Use cargo and Chinese import permits if the airline agrees',
    ],
    sourceUrl: 'https://www.csair.com/en/tourguide/special_service/pets/',
  }),
  extra('BR', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['EVA Air: hold only', 'Brachycephalic breeds not accepted', 'Taiwan import rules apply inbound'],
    sourceUrl: 'https://www.evaair.com/en-global/check-in-and-boarding/special-assistance/pets/',
  }),
  extra('CI', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['China Airlines: hold / cargo pets', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://www.china-airlines.com/us/en/fly/prepare-for-the-fly/special-assistance/pets',
  }),
  extra('HX', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 20,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Hong Kong Airlines: limited hold acceptance — confirm before booking'],
    sourceUrl: 'https://www.hongkongairlines.com/en_HK/contents/special-assistance',
  }),

  // --- South Asia ---
  extra('AI', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 5,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Air India cabin pets only if very small and on selected aircraft', LIMITED],
    sourceUrl: 'https://www.airindia.com/in/en/travel-information/special-assistance/travelling-with-pets.html',
  }),
  extra('UK', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 5,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Vistara merged into Air India — follow current Air India pet rules',
      'Cabin only for very small pets on selected flights',
    ],
    sourceUrl: 'https://www.airindia.com/in/en/travel-information/special-assistance/travelling-with-pets.html',
  }),
  extra('PK', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['PIA: hold / cargo only on most flights'],
    sourceUrl: 'https://www.piac.com.pk/experience/special-assistance',
  }),
  extra('UL', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['SriLankan Airlines: hold only', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://www.srilankan.com/en_uk/plan-and-book/special-assistance',
  }),
  extra('BG', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 20,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Biman: limited hold acceptance — confirm before booking'],
    sourceUrl: 'https://www.biman-airlines.com/',
  }),

  // --- Australia / Pacific ---
  extra('QF', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK, 'Australian biosecurity / DAFF import permits for inbound pets'],
    warnings: [
      'Qantas does not accept pets in the cabin (except assistance animals)',
      'Brachycephalic breeds not accepted as checked pets',
      'Australia has some of the world’s strictest import quarantine rules',
    ],
    sourceUrl: 'https://www.qantas.com/travel/airlines/pets/global/en',
  }),
  extra('NZ', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK, 'New Zealand MPI import permits for inbound pets'],
    warnings: [
      'Air New Zealand: no cabin pets except assistance animals',
      'Brachycephalic breeds restricted',
      'New Zealand biosecurity is extremely strict',
    ],
    sourceUrl: 'https://www.airnewzealand.com/travelling-with-pets',
  }),
  extra('VA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Virgin Australia: hold / cargo pets, not cabin', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://www.virginaustralia.com/au/en/help/special-assistance/travelling-with-pets/',
  }),
  extra('FJ', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Fiji Airways: hold / cargo only', 'Fiji biosecurity permits required inbound'],
    sourceUrl: 'https://www.fijiairways.com/en-us/plan/special-assistance',
  }),

  // --- USA / Canada ---
  extra('AA', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 9,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'American Airlines cabin pets typically under ~9 kg (20 lb) including carrier',
      'Brachycephalic breeds not accepted as checked pets',
      'International holds are more restricted than US domestic',
    ],
    sourceUrl: 'https://www.aa.com/i18n/travel-info/special-assistance/pets.jsp',
  }),
  extra('UA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 9,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'United cabin pets typically under ~9 kg including carrier',
      'Checked pets via United PetSafe; brachycephalic breeds banned from the hold',
    ],
    sourceUrl: 'https://www.united.com/en/us/fly/travel/accessibility-and-assistance/service-animals-and-pets.html',
  }),
  extra('DL', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 9,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Delta cabin pets typically under ~9 kg including carrier',
      'Brachycephalic breeds not accepted as checked pets',
    ],
    sourceUrl: 'https://www.delta.com/us/en/accessible-travel-services/service-animals-and-pets',
  }),
  extra('WN', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 9,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: [
      'Southwest: cabin only on US domestic flights',
      'No international pet transport and no hold pets',
    ],
    sourceUrl: 'https://www.southwest.com/help/booking/pets/',
  }),
  extra('AS', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 9,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Alaska: cabin for small pets; hold on selected routes', 'Brachycephalic breeds restricted in the hold'],
    sourceUrl: 'https://www.alaskaair.com/content/travel-info/accessible-services/animals',
  }),
  extra('B6', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 9,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['JetBlue: in-cabin pets only', LIMITED],
    sourceUrl: 'https://www.jetblue.com/traveling-together/traveling-with-pets',
  }),
  extra('AC', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 10,
    maxWeightHold: 45,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [
      'Air Canada cabin pets typically under 10 kg including carrier',
      'Brachycephalic breeds not accepted as checked pets',
    ],
    sourceUrl: 'https://www.aircanada.com/ca/en/aco/home/plan/special-assistance/pets.html',
  }),
  extra('WS', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 10,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['WestJet: cabin pets on most routes; cargo on selected flights only'],
    sourceUrl: 'https://www.westjet.com/en-ca/flights/special-assistance/pets',
  }),
  extra('F9', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 9,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Frontier: cabin only, small dogs/cats typically under 20 lb including carrier'],
    sourceUrl: 'https://www.flyfrontier.com/travel/travel-info/family-pets/',
  }),
  extra('NK', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 9,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Spirit: in-cabin small dogs and cats only'],
    sourceUrl: 'https://customersupport.spirit.com/en-us/category/article/KA-01355',
  }),
  extra('G4', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 9,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Allegiant: cabin only, small dogs and cats'],
    sourceUrl: 'https://www.allegiantair.com/pets',
  }),
  extra('SY', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 9,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Sun Country: in-cabin pets only'],
    sourceUrl: 'https://www.suncountry.com/flying-with-us/pets',
  }),
  extra('HA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 9,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK, 'Hawaii animal quarantine / biosecurity paperwork for inbound pets'],
    warnings: [
      'Hawaiian: cabin + cargo, with strict Hawaii biosecurity rules',
      'Brachycephalic breeds not accepted as checked pets',
    ],
    sourceUrl: 'https://www.hawaiianairlines.com/our-services/special-assistance/pets',
  }),
  extra('3M', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 7,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Silver Airways: small cabin pets on regional US flights if space allows'],
    sourceUrl: 'https://www.silverairways.com/',
  }),
  extra('KS', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 7,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Peninsula Airways: small cabin pets only if the operating aircraft allows it'],
    sourceUrl: 'https://www.penair.com/',
  }),
  extra('PD', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 8,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Porter: in-cabin small pets on most Canadian routes'],
    sourceUrl: 'https://www.flyporter.com/en-ca/travel-information/special-assistance/pets',
  }),
  extra('TS', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 10,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Air Transat: cabin and hold on selected leisure routes', LIMITED],
    sourceUrl: 'https://www.airtransat.com/en-CA/travel-information/special-assistance/pets',
  }),

  // --- Latin America ---
  extra('LA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 7,
    maxWeightHold: 45,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['LATAM: cabin + hold rules vary by country and aircraft', LIMITED],
    sourceUrl: 'https://www.latamairlines.com/us/en/experience/prepare/special-assistance/pets',
  }),
  extra('JJ', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 7,
    maxWeightHold: 45,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['LATAM Brasil (JJ) follows LATAM pet rules — confirm the operating carrier'],
    sourceUrl: 'https://www.latamairlines.com/us/en/experience/prepare/special-assistance/pets',
  }),
  extra('G3', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 10,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Gol: cabin pets mainly on Brazil domestic flights'],
    sourceUrl: 'https://www.voegol.com.br/en/information/special-assistance/pets',
  }),
  extra('AD', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 10,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Azul: cabin + hold on most Brazilian routes', LIMITED],
    sourceUrl: 'https://www.voeazul.com.br/en/information/special-assistance/pets',
  }),
  extra('AR', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: [LIMITED],
    sourceUrl: 'https://www.aerolineas.com.ar/en-us/information/special_assistance/pets',
  }),
  extra('CM', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Copa: cabin + hold; Panama transit rules may apply', LIMITED],
    sourceUrl: 'https://www.copaair.com/en/web/gs/pets',
  }),
  extra('AV', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Avianca: cabin + hold, varies by route and aircraft', LIMITED],
    sourceUrl: 'https://www.avianca.com/en/travel-information/special-assistance/pets/',
  }),
  extra('AM', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 9,
    maxWeightHold: 45,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Aeroméxico: cabin + hold', LIMITED],
    sourceUrl: 'https://www.aeromexico.com/en-us/travel-information/special-assistance/pets',
  }),
  extra('Y4', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: false,
    maxWeightCabin: 10,
    brachycephalicBanned: false,
    requirements: ['Carrier must fit under the seat', PREBOOK],
    warnings: ['Volaris: in-cabin pets on most Mexican routes'],
    sourceUrl: 'https://www.volaris.com/en/travel-info/pets',
  }),

  // --- Caribbean ---
  extra('BW', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 7,
    maxWeightHold: 20,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Caribbean Airlines: limited cabin/hold — confirm island import rules'],
    sourceUrl: 'https://www.caribbean-airlines.com/#/travel-information/special-assistance',
  }),
  extra('WM', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: false,
    requirements: [],
    warnings: ['Winair aircraft are small island hoppers — pets are generally not accepted', ASSIST_ONLY],
    sourceUrl: 'https://www.fly-winair.sx/',
  }),
  extra('8J', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: false,
    requirements: [],
    warnings: ['Verify the operating carrier on your ticket before assuming pet acceptance', ASSIST_ONLY],
    sourceUrl: 'https://www.iata.org/en/programs/cargo/live-animals/',
  }),

  // --- Africa ---
  extra('ET', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Ethiopian Airlines: hold / cargo pets', 'Brachycephalic breeds often refused'],
    sourceUrl: 'https://www.ethiopianairlines.com/aa/information/special-assistance/pets',
  }),
  extra('SA', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['South African Airways: hold / cargo', 'Brachycephalic breeds restricted'],
    sourceUrl: 'https://www.flysaa.com/manage-fly/special-assistance/pets',
  }),
  extra('KQ', {
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Kenya Airways: hold / cargo pets'],
    sourceUrl: 'https://www.kenya-airways.com/en-ke/travel-information/special-assistance/pets/',
  }),
  extra('AT', {
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 5,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [...STD_REQ, PREBOOK],
    warnings: ['Royal Air Maroc: small cabin pets on selected flights', LIMITED],
    sourceUrl: 'https://www.royalairmaroc.com/int-en/information/special-assistance/pets',
  }),
];

export const PET_RULES: PetRule[] = [
  {
    airlineIata: 'TG',
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'DLD import permit for Thailand (14–45 days in advance)',
    ],
    warnings: [
      'No pets in the cabin on Thai Airways',
      'Brachycephalic breeds (bulldog, pug) not allowed in the hold',
      'Max 2 animals per flight in the hold',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.thaiairways.com/en/plan_my_trip/travel_information/pets.page',
  },
  {
    airlineIata: 'KL',
    animalTypes: ['dog_small', 'cat', 'rabbit'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 75,
    brachycephalicBanned: false,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
    ],
    warnings: [
      'Max 1 pet per passenger in the cabin',
      'Pre-register with KLM (not via the app)',
      'Limited spaces per flight',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.klm.com/nl/nl/information/pets',
  },
  {
    airlineIata: 'LH',
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 45,
    brachycephalicBanned: false,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'Pre-register with Lufthansa',
    ],
    warnings: [
      'Cabin only up to 8 kg including crate',
      'Brachycephalic breeds (bulldog, pug) not allowed in summer',
      'Limited pets per flight',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.lufthansa.com/nl/en/travelling-with-animals',
  },
  {
    airlineIata: 'SQ',
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'Pre-register with Singapore Airlines',
    ],
    warnings: [
      'No pets in the cabin on Singapore Airlines',
      'Dogs and cats in the hold only',
      'Brachycephalic breeds not allowed',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.singaporeair.com/en_UK/sg/travel-info/special-assistance/travelling-with-pets/',
  },
  {
    airlineIata: 'EK',
    animalTypes: ['dog_small', 'dog_large', 'cat'],
    cabinAllowed: false,
    holdAllowed: true,
    maxWeightHold: 32,
    brachycephalicBanned: true,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'Pre-register via Emirates Cargo / SkyCargo',
    ],
    warnings: [
      'No pets in the cabin on Emirates',
      'Dogs and cats in the hold only',
      'Brachycephalic breeds not allowed',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.emirates.com/english/help/faq-topics/baggage/travelling-with-pets/',
  },
  {
    airlineIata: 'QR',
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 7,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'Pre-register with Qatar Airways',
    ],
    warnings: [
      'Cabin only up to 7 kg including crate',
      'Dogs and cats only',
      'Limited spaces per flight',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.qatarairways.com/en/baggage/pets.html',
  },
  {
    airlineIata: 'EY',
    animalTypes: ['dog_small', 'cat'],
    cabinAllowed: true,
    holdAllowed: true,
    maxWeightCabin: 8,
    maxWeightHold: 32,
    brachycephalicBanned: false,
    requirements: [
      'Health certificate (max 10 days old)',
      'Approved IATA crate',
      'Rabies vaccination',
      'Microchip (ISO 11784/11785)',
      'Pre-register with Etihad',
    ],
    warnings: [
      'Cabin only up to 8 kg including crate',
      'Max 1 pet per passenger in the cabin',
      'Limited spaces per flight',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.etihad.com/en-nl/fly-etihad/special-assistance/travelling-with-pets',
  },
  {
    airlineIata: 'FD',
    animalTypes: ['dog_small', 'dog_large', 'cat', 'rabbit', 'bird', 'reptile', 'other'],
    cabinAllowed: false,
    holdAllowed: false,
    brachycephalicBanned: false,
    requirements: [],
    warnings: [
      'AirAsia does not carry pets in the cabin or hold',
      'No exception for small pets or service animals via this channel',
    ],
    lastVerified: '2026-08-01',
    sourceUrl: 'https://www.airasia.com/aa/about-us/en/gb/conditions-of-carriage.html',
  },
  ...EXTRA_RULES,
].map(withImportDefaults);
