export const PET_STRINGS = {
  sheetTitle1: '🐾 Which animal is travelling?',
  sheetTitle2: '⚖️ Weight and breed',
  sheetTitle3: 'Result',
  stepIndicator: (step: number) => `${step}/3`,
  resultCabin: 'Allowed in cabin',
  resultHold: 'Hold only',
  resultNotAllowed: 'Not allowed',
  resultUnknown: 'Unknown — check with airline',
  requirementsTitle: 'What you need',
  warningsTitle: 'Please note',
  disclaimerTitle: '⚠️ Important',
  disclaimerText:
    'This information is indicative and may be outdated. Rules change without prior notice. Always verify current requirements with your airline, your own government, and the authorities of your destination country. WaiAir accepts no liability.',
  sourceText: (date: string) => `Verified on ${date} · View official source ↗`,
  petButtonText: '🐾  Is your pet travelling on this flight?',
  horseTitle: 'Horses travel via charter flights',
  horseText:
    'Horses are not transported on commercial flights. Transport is arranged via specialised charter flights under IATA Live Animals Regulations.\n\nContact a specialist:\n• Peden Bloodstock\n• IRT (International Racetrack Transport)\n• Air Horse One',
  horseDisclaimer:
    '⚠️ WaiAir accepts no liability. Always verify with your own government and destination country.',
  unknownAirline: (iata: string) =>
    `No data for ${iata} — please check the airline website.`,
  animalDogSmall: 'Small dog (<8kg)',
  animalDogLarge: 'Large dog (>8kg)',
  animalCat: 'Cat',
  animalRabbit: 'Rabbit',
  animalBird: 'Bird',
  animalOther: 'Other',
  animalHorse: 'Horse',
  weightLabel: (kg: number) => `${kg} kg`,
  brachyLabel: 'Short-nosed breed (bulldog, pug)?',
  confirmCheck: 'Check',
  back: 'Back',
  nextStepsTitle: 'Next steps',
  actionHotel: 'Book pet-friendly hotel',
  actionTransfer: 'Pet-friendly transfer',
  actionDocuments: 'My documents',
  actionScan: 'Scan document',
  actionContacts: 'Local pet contacts',
  documentsSoon: 'Coming soon — document storage',
  documentsSoonHint: 'You will be able to keep health certificates, rabies records and import permits here.',
  cameraNeedPermission: 'Camera access is needed to scan your document.',
  allowCamera: 'Allow camera',
  cameraInApps: 'Camera scanning is available in the iOS and Android apps.',
  capturePhoto: 'Take photo',
  photoSaved: 'Photo saved to your library',
  photoSaveFailed: 'Could not save the photo. Check Photos permission and try again.',
  close: 'Close',
  contactsHint: 'Tap a number to call. Always confirm locally — numbers can change.',
  contactsNoMatch: 'No dedicated listing for this airport yet — major hubs below.',
};
